# Generated by Django 5.2 on 2025-05-01 13:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
